[package]
name = "hap-rs-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
hap-rs = { path = "..", features = ["fuzzing"] }

[[bin]]
name = "vcf"
path = "fuzz_targets/vcf.rs"
test = false
doc = false
bench = false

[[bin]]
name = "bcf"
path = "fuzz_targets/bcf.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fasta"
path = "fuzz_targets/fasta.rs"
test = false
doc = false
bench = false

[[bin]]
name = "bed"
path = "fuzz_targets/bed.rs"
test = false
doc = false
bench = false

[[bin]]
name = "location"
path = "fuzz_targets/location.rs"
test = false
doc = false
bench = false
